/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moviebooking;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import moviebooking.entities.Booking;
import moviebooking.entities.BookingDAO;
import moviebooking.entities.User;

/**
 *
 * @author Parth Shah
 */
public class History extends javax.swing.JFrame {

    /**
     * Creates new form History
     */
    public History(User user) {
        initComponents();
        int i=0;
        //DefaultTableModel dm = (DefaultTableModel)getModel();
        ArrayList<Booking> bookings = BookingDAO.getBookings(user);
        
        int c = bookings.size();
        String[] columns = new String[] {
            "Booking ID","Movie Name","Theater","Show Date","Show Time","Amount"
        };
        
        Object[][] data = new Object[c][6];
        
        
        for(Booking booking : bookings){
            data[i] = new Object[6];
            data[i][0] = String.valueOf(booking.getId());
            data[i][1] = String.valueOf(booking.getShow().getMovie().getName());
            data[i][2] = String.valueOf(booking.getShow().getTheater().getName());
            data[i][3] = String.valueOf(booking.getShow().getDate().format(DateTimeFormatter.ofPattern("dd/MM/yy")));
            data[i][4] = String.valueOf(booking.getShow().getTime()) + ":00";
            data[i][5] = String.valueOf(booking.getShow().getAmount());
            i++;
        }
        
        DefaultTableModel model = new DefaultTableModel(data,columns);
        
        /*for(Object[] o : data){
            model.addRow(o);
        }*/
        
        bookingTable.setModel(model);
        bookingTable.setEnabled(false);
        
        backToUser.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new UserHome(user).setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookingTable = new javax.swing.JTable();
        backToUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bookings");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 285, 46));

        bookingTable.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        bookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Movie Name", "Theater", "Show Date", "Show Time", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(bookingTable);
        if (bookingTable.getColumnModel().getColumnCount() > 0) {
            bookingTable.getColumnModel().getColumn(0).setResizable(false);
            bookingTable.getColumnModel().getColumn(1).setResizable(false);
            bookingTable.getColumnModel().getColumn(2).setResizable(false);
            bookingTable.getColumnModel().getColumn(3).setResizable(false);
            bookingTable.getColumnModel().getColumn(4).setResizable(false);
            bookingTable.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 680, 390));

        backToUser.setBackground(new java.awt.Color(255, 255, 255));
        backToUser.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        backToUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Left Arrow.png"))); // NOI18N
        backToUser.setText("Back to Home");
        backToUser.setBorder(null);
        backToUser.setBorderPainted(false);
        backToUser.setContentAreaFilled(false);
        backToUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backToUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        backToUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToUserActionPerformed(evt);
            }
        });
        jPanel1.add(backToUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backToUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backToUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //  new History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToUser;
    private javax.swing.JTable bookingTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
