/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moviebooking;

import java.time.format.DateTimeFormatter;
import moviebooking.entities.Booking;

/**
 *
 * @author Maulik
 */
public class Receipt extends javax.swing.JFrame {

    /**
     * Creates new form Receipt
     */
    public Receipt(Booking booking) {
        initComponents();
        movie.setText(booking.getShow().getMovie().getName());
        theatre.setText(booking.getShow().getTheater().getName());
        time.setText(booking.getShow().getTime().toString()+":00");
        amount.setText("Rs. "+String.valueOf(booking.getShow().getAmount()+"/-"));
        date.setText(booking.getShow().getDate().format(DateTimeFormatter.ofPattern("dd/MM/yy")));       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        movie = new javax.swing.JLabel();
        theatre = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        movie.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        movie.setText("Movie Name");
        jPanel1.add(movie, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 240, 50));

        theatre.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        theatre.setText("Theatre Name");
        jPanel1.add(theatre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 230, 30));

        time.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        time.setText("Timing");
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 130, 30));

        amount.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        amount.setText("Amount");
        jPanel1.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 100, 30));

        date.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        date.setText("Date");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/TicketTemplate.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 270));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel movie;
    private javax.swing.JLabel theatre;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
