/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moviebooking;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import moviebooking.entities.User;
import moviebooking.entities.UserDAO;
import static moviebooking.entities.UserDAO.getUser;

/**
 *
 * @author Parth Shah
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        signUp.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                //if validate true
                //username same
                User u = getUser(username.getText());
                if(u != null)
                {
                    JOptionPane.showMessageDialog(null,"Username already taken","Sign Up Error",JOptionPane.PLAIN_MESSAGE);
                    name.setText("");
                    username.setText("");
                    password.setText("");
                }
                //blank
                else if((name.getText().equals(""))||(username.getText().equals(""))||(String.valueOf(password.getPassword()).equals("")))
                {
                    JOptionPane.showMessageDialog(null,"Field(s) cannot be empty","Sign Up Error",JOptionPane.PLAIN_MESSAGE);
                }
                else
                {
                    User user = new User(name.getText(), username.getText(), String.valueOf(password.getPassword()),0);
                    UserDAO.save(user);
                    JOptionPane.showMessageDialog(null,"You have Registered Successfully. Please Log in!","Registration Successful",JOptionPane.PLAIN_MESSAGE);
                    dispose();
                    new Login().setVisible(true);
                }
            }
        });
        
        login.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                dispose();
                new Login().setVisible(true);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        login = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        signUp = new javax.swing.JButton();

        dateChooserDialog2.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setBackground(new java.awt.Color(255, 255, 255));
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel5.setBackground(java.awt.Color.white);
    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/DoggoSmall.png"))); // NOI18N
    jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    jLabel5.setOpaque(true);
    jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 570));

    jLabel6.setText("jLabel6");
    jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 20, 530));

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -3, 510, 530));

    jPanel2.setBackground(new java.awt.Color(255, 255, 255));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    login.setBackground(new java.awt.Color(255, 255, 255));
    login.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
    login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Left Arrow.png"))); // NOI18N
    login.setText("Back to Login");
    login.setBorder(null);
    login.setBorderPainted(false);
    login.setContentAreaFilled(false);
    login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    login.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    login.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            loginActionPerformed(evt);
        }
    });
    jPanel2.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 50));

    password.setBackground(new java.awt.Color(204, 204, 204));
    password.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
    password.setBorder(null);
    password.setOpaque(false);
    jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 230, 30));

    jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
    jLabel4.setText("Password");
    jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

    jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
    jLabel3.setText("Username");
    jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

    username.setBackground(new java.awt.Color(204, 204, 204));
    username.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
    username.setBorder(null);
    username.setOpaque(false);
    username.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            usernameActionPerformed(evt);
        }
    });
    jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 230, 30));

    name.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
    name.setBorder(null);
    name.setDisabledTextColor(new java.awt.Color(255, 255, 255));
    name.setOpaque(false);
    name.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            nameActionPerformed(evt);
        }
    });
    jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 230, 30));

    jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
    jLabel2.setText("Name");
    jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

    jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("REGISTER");
    jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 510, -1));

    jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
    jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 230, 10));

    jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
    jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 230, 10));

    jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
    jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 230, 10));

    signUp.setBackground(new java.awt.Color(204, 204, 204));
    signUp.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
    signUp.setText("Sign Me Up!");
    signUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jPanel2.add(signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 230, 40));

    getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 510, 530));

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton login;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton signUp;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}